---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 125

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

#########
# RSPEC #
#########

RSpec/InstanceVariable:
  Enabled: false
