AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*

Documentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/LineLength:
  Max: 110
