language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.1
  - 2.5.3
  - 2.4.5
before_install:
  - gem update --system
  - gem install bundler --no-document
gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.2.gemfile
